version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: react
    networks:
      - linne_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./server:/usr/src/app
    container_name: express
    command: npx nodemon --legacy-watch index.ts
    networks:
      - linne_network

networks:
  linne_network:
    driver: bridge
