version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: React

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./server:/usr/src/app
    container_name: Express
    command: npx nodemon --legacy-watch index.ts
